### ISSUE TITLE
[Feature] How to manually install this plugin?

### ISSUE THREAD

**Issue by thbourlove** [ilgizar/ilgizar-candlestick-panel#11]
how to manually install this plugin with `grafana-cli plugins install` ?

**Comment by kke** [comment]
Why closed?

Automatic travis build + release would be nice.

**Comment by ilgizar** [comment]
the author of this issue himself closed. I think he understood how to do it. Automatic travis build placed on directory "pack". Use official install instruction, link on main page.

**Comment by kke** [comment]
Oh it's in there. I don't see any hints on the README or the official install docs that I should look into a directory called pack :)

When releasing, you should create a git tag and upload the binary to the [release page](https://github.com/ilgizar/ilgizar-candlestick-panel/releases).

You can configure travis to do this for you automatically when you push a commit with tags.

**Comment by parkview** [comment]
I have useed git to place the candlestick module manually into the Grafana plugin folder.  After restarting Grafana, I can see the Candlestick plugin, but when I drag it onto a Panel, I get something like this popup error:

Plugin Error unable to dynamicly transpile ES module a loader plugin needs to be configured via `systemjs.config{{transpiler:'traspiler-module'}}'.

Googleing this I see comments about missing Babel, yet there is no mention of other dependencies being needed.  Any clues with what is going on?  I am not seeing any errors in the grafana log system (but I am new to Grafana.  Running Grafana 4.6.2
![image](https://user-images.githubusercontent.com/5894800/37600511-856cdefc-2bc2-11e8-899d-0ff7378f4ca4.png)

**Comment by JamesGalt** [comment]
@parkview 
go to your grafana plugin folder
`wget https://github.com/ilgizar/ilgizar-candlestick-panel/raw/master/pack/ilgizar-candlestick-panel.zip`
`unzip ilgizar-candlestick-panel.zip`
`systemctl restart grafana-server`

**Comment by ilgizar** [comment]
@parkview 
In the general case @JamesGalt`s instruction is true.
I checked the plugin on version 4.6.2 - ok.
1. create grafana lib folder
`mkdir -p /var/grafana/lib-4.6.2`
2. install grafana 4.6.2 on docker
`docker run -d --name grafana-4.6.2 -v /var/grafana/lib-4.6.2:/var/lib/grafana:rw -p 3001:3000 grafana/grafana:4.6.2`
3. download and unpack plugin
`cd /var/grafana/lib-4.6.2/plugins`
`wget https://github.com/ilgizar/ilgizar-candlestick-panel/raw/master/pack/ilgizar-candlestick-panel.zip`
`unzip ilgizar-candlestick-panel.zip`
`rm /var/grafana/lib-4.6.2`
4. restart grafana docker
`docker restart grafana-4.6.2`
5. login to grafana http://127.0.0.1:3001 with account admin:admin
6. add data source
7. create dashboard with candlestick graph
8. add 4 metrics: open, close, low, high

**Comment by parkview** [comment]
Thanks for your replies @JamesGalt and @ilgizar.  While I have the done steps 1-6 (non Docker, FreeBSD 11.1 based server), the above screenshot appears when I attempt to do step 7: drag the Candlestick panel onto the Dashboard.

With just a quick peek under the hood, I see that file:  Gruntfile.js  mentions Grunt and Babel.  I don't have them installed on my server, so unless they come pre-built with Candlestick or Grafana, they are not accessible.  Should they be?

Otherwise, why and what is the screenshot error msg talking about?  Thanks.

**Comment by ilgizar** [comment]
Gruntfile.js is used when creating the plugin, it does not need to work. Do not pay attention to this file.
That causes you the error is not clear.

**Comment by tux-00** [comment]
@ilgizar I have the same error (screenshot above) with version 5.1.2 & 5.1.3.
