### ISSUE TITLE
[BUG] indicators options messed up when adding a new indicator

### ISSUE THREAD

**Issue by JamesGalt** [ilgizar/ilgizar-candlestick-panel#13]
Hi
Thanks for adding the feature.
There is a bug when you add indicators the options list get mixed up, see screenshots below

Before
<img width="830" alt="capture d ecran 2018-03-31 a 01 25 58" src="https://user-images.githubusercontent.com/13592957/38156972-a0afc602-3482-11e8-9008-01a88de735ae.png">

After adding 
<img width="842" alt="capture d ecran 2018-03-31 a 01 26 23" src="https://user-images.githubusercontent.com/13592957/38156977-af647ae4-3482-11e8-9929-82ef1eb4bab5.png">

**Comment by ilgizar** [comment]
Yes, I saw this bug.

**Comment by JamesGalt** [comment]
Hi,
Any planing on correcting this?
Thanks
