### ISSUE TITLE
[Bug] Erratic chart

### ISSUE THREAD

**Issue by JamesGalt** [ilgizar/ilgizar-candlestick-panel#2]
Hi,
I have missing plots in the graf
same version of grafana
see the tooltip in the following screenshot
<img width="1428" alt="capture d ecran 2018-02-22 a 03 26 25" src="https://user-images.githubusercontent.com/13592957/36516928-713d1f38-1780-11e8-905f-4869b84f11e3.png">
Thanks

**Comment by ilgizar** [comment]
What data source? How do you ask for metrics?
I assume that in the designated period there is no data in the database. Reduce the period to the gap with the missing schedule and send the raw data of one of the metrics.
To fill in the missing data, you can use **fill(linear)** in **GROUP BY** section.

**Comment by JamesGalt** [comment]
Data source is Influx, and there is data as you can see in the tooltip, I can show you the data in the graph panel
As you can see there is volume
Also I already used fill(previous)
I use a custom interval named $itv because I want to be able to select custom values.
__$interval seems to work but is not settable by user :(
<img width="1410" alt="capture d ecran 2018-02-22 a 05 00 53" src="https://user-images.githubusercontent.com/13592957/36519739-7be1a744-178d-11e8-9473-dc9c784ac4b9.png">
<img width="1428" alt="capture d ecran 2018-02-22 a 05 13 50" src="https://user-images.githubusercontent.com/13592957/36520084-4bb8a412-178f-11e8-888e-2c0ab8988b11.png">

**Comment by JamesGalt** [comment]
This is what I get when I use the built in __$interval variable
as you can see there are volume so it should draw data
I suspect the data being too high as you can see in my screenshot
Also I can send you the json data from the query inspector
<img width="1423" alt="capture d ecran 2018-02-22 a 05 33 16" src="https://user-images.githubusercontent.com/13592957/36520556-ef03cd20-1791-11e8-89ab-c0729e258855.png">

**Comment by JamesGalt** [comment]
I ve been able to reproduce it, when there is a spike with high over the maximum of open or close it doesn't show the box but data are here, we can see it in the tooltip as in the screenshot above.

data that makes the plotting fail
[data.json](https://gist.githubusercontent.com/JamesGalt/ccca26ecd26fbb76e1e8e39801782f3f/raw/6d25feafed8d5e6222c3e43364a3d9aea1937769/data.json)

**Comment by ilgizar** [comment]
Thank you, your data made it possible to identify a mistake in the plugin's work of rendering candlesticks.

**Comment by JamesGalt** [comment]
Happy to help!

**Comment by JamesGalt** [comment]
Perfect !
